DECLARE 
   VAR_CONTACT_NAME VARCHAR2(2000); 
   VAR_TELEPHONE_NUMBER VARCHAR2(2000);
   VAR_MOBILE_NUMBER VARCHAR2(2000);
   VAR_ORDERS VARCHAR2(2000);
   VAR_TOTAL_AMOUNT VARCHAR2(2000);
 
   CURSOR CUR_SUPPLIER_LIST is 
      SELECT * FROM XXBCM_SUPPLIER_LIST; 
BEGIN 
   OPEN CUR_SUPPLIER_LIST; 
   LOOP 
   FETCH CUR_SUPPLIER_LIST into     VAR_CONTACT_NAME , VAR_TELEPHONE_NUMBER ,VAR_MOBILE_NUMBER ,VAR_ORDERS ,VAR_TOTAL_AMOUNT ; 
      EXIT WHEN CUR_SUPPLIER_LIST%notfound; 
              DBMS_OUTPUT.PUT_LINE('Contrat Name: ' || VAR_CONTACT_NAME);
        DBMS_OUTPUT.PUT_LINE('Telephone Number  : ' || VAR_TELEPHONE_NUMBER);
        DBMS_OUTPUT.PUT_LINE('Mobile Number : ' || VAR_MOBILE_NUMBER);
        DBMS_OUTPUT.PUT_LINE('Orders : ' || VAR_ORDERS);
        DBMS_OUTPUT.PUT_LINE('Total Amount: ' || VAR_TOTAL_AMOUNT);
	    DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('*******************************************'); END LOOP; 
   CLOSE CUR_SUPPLIER_LIST; 
END; 
/