DECLARE 
   VAR_ORDER_REF VARCHAR2(2000); 
   VAR_ORDER_DATE VARCHAR2(2000);
   VAR_SUPPLIER_NAME VARCHAR2(2000);
   VAR_TOTAL_AMT VARCHAR2(2000);
   VAR_ORDER_STATUS VARCHAR2(2000);
   VAR_INVOICE_REF VARCHAR2(2000);
   VAR_INVOICE_AMT VARCHAR2(2000);
   VAR_INVOICE_STATUS VARCHAR2(2000);
   VAR_ACTION VARCHAR2(2000);
   CURSOR CUR_ORDER_SUMMARY is 
      SELECT * FROM XXBCM_ORDER_SUMMARY; 
BEGIN 
   OPEN CUR_ORDER_SUMMARY; 
   LOOP 
   FETCH CUR_ORDER_SUMMARY into    VAR_ORDER_REF , VAR_ORDER_DATE ,VAR_SUPPLIER_NAME , VAR_TOTAL_AMT , VAR_ORDER_STATUS , VAR_INVOICE_REF , VAR_INVOICE_AMT , VAR_INVOICE_STATUS ,  VAR_ACTION ; 
      EXIT WHEN CUR_ORDER_SUMMARY%notfound; 
              DBMS_OUTPUT.PUT_LINE('Order Reference : ' || VAR_ORDER_REF);
        DBMS_OUTPUT.PUT_LINE('Order Date : ' || VAR_ORDER_DATE);
        DBMS_OUTPUT.PUT_LINE('Supplier Name : ' || VAR_SUPPLIER_NAME);
        DBMS_OUTPUT.PUT_LINE('Order Total Amount : ' || VAR_TOTAL_AMT);
        DBMS_OUTPUT.PUT_LINE('Order Status : ' || VAR_ORDER_STATUS);
        DBMS_OUTPUT.PUT_LINE('Invoice Reference : ' || VAR_INVOICE_REF);
        DBMS_OUTPUT.PUT_LINE('Invoice Total Amount : ' || VAR_INVOICE_AMT);
        DBMS_OUTPUT.PUT_LINE('Invoice Status : ' || VAR_INVOICE_STATUS);
		DBMS_OUTPUT.PUT_LINE('Action : ' || VAR_ACTION);
        DBMS_OUTPUT.PUT_LINE('');
		 DBMS_OUTPUT.PUT_LINE('*******************************************'); END LOOP; 
   CLOSE CUR_ORDER_SUMMARY; 
END; 
/


       