DECLARE 
   VAR_ORDER_REF VARCHAR2(2000); 
   VAR_ORDER_DATE VARCHAR2(2000);
   VAR_SUPPLIER_NAME VARCHAR2(2000);
   VAR_TOTAL_AMT VARCHAR2(2000);
   VAR_ORDER_STATUS VARCHAR2(2000);
   VAR_INVOICE VARCHAR2(2000);
   CURSOR CUR_THIRD_HIGHEST is 
      SELECT * FROM XXBCM_THIRD_HIGHEST; 
BEGIN 
   OPEN CUR_THIRD_HIGHEST; 
   LOOP 
   FETCH CUR_THIRD_HIGHEST into    VAR_ORDER_REF , VAR_ORDER_DATE ,VAR_SUPPLIER_NAME , VAR_TOTAL_AMT , VAR_ORDER_STATUS ,VAR_INVOICE ; 
      EXIT WHEN CUR_THIRD_HIGHEST%notfound; 
              DBMS_OUTPUT.PUT_LINE('Order Reference : ' || VAR_ORDER_REF);
        DBMS_OUTPUT.PUT_LINE('Order Date : ' || VAR_ORDER_DATE);
        DBMS_OUTPUT.PUT_LINE('Supplier Name : ' || VAR_SUPPLIER_NAME);
        DBMS_OUTPUT.PUT_LINE('Order Total Amount : ' || VAR_TOTAL_AMT);
        DBMS_OUTPUT.PUT_LINE('Order Status : ' || VAR_ORDER_STATUS);
		DBMS_OUTPUT.PUT_LINE('INVOICES : ' || VAR_INVOICE);
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('*******************************************'); END LOOP; 
   CLOSE CUR_THIRD_HIGHEST; 
END; 
/